# Generated by Django 3.0.8 on 2020-07-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200722_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='meals',
            new_name='meal',
        ),
    ]
