# Generated by Django 3.0.8 on 2020-08-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200722_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
